* Riak C/C++ Client

* READ THIS

This is experimental, alpha code. If you're running it in production, you do so at your own risk. While Basho fully intends
to work on this when our development cycle permits, at the moment this libary is still very young and is in no way complete.  
In its current state, it will break, and there will be bugs.

That said, we do want for it to become a first class citizen in our Client Library arsenal at some point. With your help, 
this will be sooner than later. 

** Overview

This is a WIP of a C/C++ client for Riak. 

- [[https://github.com/basho/riak-cxx-client/blob/master/riak_client/cxx/basic/basic_client.hpp][Basic API]]
- [[https://github.com/basho/riak-cxx-client/blob/master/riak_client/cxx/client/client.hpp][High-level client API]]
- [[https://github.com/basho/riak-cxx-client/blob/master/riak_client/client.h][C API]]
- [[https://github.com/basho/riak-cxx-client/blob/master/test/test_basic.cpp][Sample Code]]

#+BEGIN_SRC shell

/* fetch an object */
riak::client_ptr c = riak::new_client("127.0.0.1", "8087");
riak::fetch_result fr = c->fetch("mybucket", "mykey", 2);
riak::object_ptr o = fr.choose_sibling(0);
assert(o->key() == "mykey");

#+END_SRC

- protobufs only
- no links or MR
- basic client and high-level client inspired by the new java client
- basic client is complete, high-level client in progress
- C wrapper in progress
- embedded deps (protobufs, boost::asio)
- autotools build
- needs WAY more tests




Minimal API documentation is available at [[http://argv0.github.com/riak-cxx-client][Github]].

** Quick Start

#+BEGIN_SRC shell
./configure
make
make check
sudo make install
#+END_SRC

** Contributing
   We encourage contributions from the community.

   1) Fork the =riak-cxx-client= repository on [[https://github.com/basho/riak-cxx-client][Github]].
   2) Clone your fork or add the remote if you already have a clone of
      the repository.
#+BEGIN_SRC shell
git clone git@github.com:yourusername/riak-cxx-client.git
# or
git remote add mine git@github.com:yourusername/riak-cxx-client.git
#+END_SRC
   3) Create a topic branch for your change.
#+BEGIN_SRC shell
git checkout -b some-topic-branch
#+END_SRC
   4) Make your change and commit. Use a clear and descriptive commit
      message, spanning multiple lines if detailed explanation is
      needed.
   5) Push to your fork of the repository and then send a pull-request
      through Github.
#+BEGIN_SRC shell
git push mine some-topic-branch
#+END_SRC
   6) A Basho engineer or community maintainer will review your patch
      and merge it into the main repository or send you feedback.
